/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author 13151000014
 */
public class CadFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadFuncionario
     */
    public CadFuncionario() {
        initComponents();
    }
    
    public CadFuncionario(String nome, String end, String cpf, String telefone, String salario, String data, String email) {
        initComponents();
        this.jtfNome.setText(nome);
        this.jtfEndereco.setText(end);
        this.jftfCPF.setText(cpf);
        this.jtfTelefone.setText(telefone);
        this.jtfSalario.setText(salario);
        this.jftfData.setText(data);
        this.jtfEmail.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlCadastroFuncionario = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        jlSalario = new javax.swing.JLabel();
        jtfSalario = new javax.swing.JTextField();
        jlData = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jftfCPF = new javax.swing.JFormattedTextField();
        jftfData = new javax.swing.JFormattedTextField();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(99, 113, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCadastroFuncionario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlCadastroFuncionario.setText("Cadastro de Funcionários");
        jPanel1.add(jlCadastroFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, 30));

        jlNome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlNome.setText("Nome:");
        jPanel1.add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel1.add(jtfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 210, -1));

        jlEndereco.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlEndereco.setText("Endereço:");
        jPanel1.add(jlEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));
        jPanel1.add(jtfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 210, -1));

        jlCPF.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlCPF.setText("CPF:");
        jPanel1.add(jlCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jlTelefone.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlTelefone.setText("Telefone:");
        jPanel1.add(jlTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jtfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jtfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 210, -1));

        jlSalario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlSalario.setText("Salario:");
        jPanel1.add(jlSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jtfSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSalarioActionPerformed(evt);
            }
        });
        jPanel1.add(jtfSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 210, -1));

        jlData.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlData.setText("Data(ano/mes/dia):");
        jPanel1.add(jlData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jlEmail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlEmail.setText("E-mail:");
        jPanel1.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel1.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, -1));

        try {
            jftfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jftfCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, -1));

        try {
            jftfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfDataActionPerformed(evt);
            }
        });
        jPanel1.add(jftfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, -1));

        jbCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        if(FramePrincipal.CodAlterar!=0){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn;
                conn = DriverManager.getConnection("jdbc:mysql://localhost/dbautopecas", "root", "");               
                String query = "UPDATE funcionario SET nomeFuncionario = ?, endFuncionario = ?, cpfFuncionario = ?, telefoneFuncionario = ?, salarioFUncionario = ?, dataFuncionario = ?, emailFuncionario = ? WHERE idfuncionario = ?";
                PreparedStatement comando = conn.prepareStatement(query);
                comando.setString(1 , jtfNome.getText());
                comando.setString(2 , jtfEndereco.getText());
                comando.setString(3, jftfCPF.getText());
                comando.setString(4, jtfTelefone.getText());
                comando.setString(5, jtfSalario.getText());
                comando.setString(6, jftfData.getText());
                comando.setString(7, jtfEmail.getText());
                
                comando.setInt(8 , FramePrincipal.CodAlterar);

                comando.executeUpdate();
                
                comando.close();
                conn.close();
                
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");
                jtfNome.setText("");
                jtfEndereco.setText("");
                jftfCPF.setText("");
                jtfTelefone.setText("");
                jtfSalario.setText("");
                jftfData.setText("");
                jtfEmail.setText("");
                

            }catch (ClassNotFoundException ex) {
              JOptionPane.showMessageDialog(null, "Não foi possível encontrar a classe Driver!");
            } catch (SQLException ex2) {
             JOptionPane.showMessageDialog(null, "Ocorreu um erro interno de SQL!"+ex2);
            }
            FramePrincipal.CodAlterar = 0;
        }else{
            try{

                Class.forName("com.mysql.jdbc.Driver"); 

                Connection conexao;

                conexao = DriverManager.getConnection("jdbc:mysql://localhost/dbautopecas","root","");

                String comando = "INSERT into funcionario (nomeFuncionario, endFuncionario, cpfFuncionario, telefoneFuncionario, salarioFuncionario, dataFuncionario, emailFuncionario)VALUES (?,?,?,?,?,?,?)";

                java.sql.PreparedStatement stmt = conexao.prepareStatement(comando);

                stmt.setString(1, jtfNome.getText()); 
                stmt.setString(2, jtfEndereco.getText());
                stmt.setString(3, jftfCPF.getText());
                stmt.setString(5, jtfSalario.getText());
                stmt.setString(4, jtfTelefone.getText());
                stmt.setString(6, jftfData.getText());
                stmt.setString(7, jtfEmail.getText());

                stmt.executeUpdate();

                stmt.close();
                conexao.close();

                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                jtfNome.setText("");
                jtfEndereco.setText("");
                jftfCPF.setText("");
                jtfSalario.setText("");
                jtfTelefone.setText("");
                jftfData.setText("");
                jtfEmail.setText("");


            }
            catch(ClassNotFoundException exClass){
                JOptionPane.showMessageDialog(null, "A classe Driver não foi encontrada!"+exClass);
            }catch(SQLException exSQL){
                JOptionPane.showMessageDialog(null, "Erro de SQL!"+exSQL);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefoneActionPerformed

    private void jftfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfDataActionPerformed

    private void jtfSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JFormattedTextField jftfCPF;
    private javax.swing.JFormattedTextField jftfData;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCadastroFuncionario;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfSalario;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
