/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author 13151000014
 */
public class CadFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadFornecedor
     */
    public CadFornecedor() {
        initComponents();
    }
    
    public CadFornecedor(String nome, String telefone, String email) {
        initComponents();
        this.jtfNome.setText(nome);
        this.jtfTelefone.setText(telefone);
        this.jtfEmail.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlCadastroFornecedor = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfCadastrar = new javax.swing.JButton();
        jtfCancelar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(99, 113, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCadastroFornecedor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlCadastroFornecedor.setText("Cadastro de Fornecedor");
        jPanel1.add(jlCadastroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jlNome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlNome.setText("Nome:");
        jPanel1.add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jlTelefone.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlTelefone.setText("Telefone:");
        jPanel1.add(jlTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jlEmail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlEmail.setText("E-mail:");
        jPanel1.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jtfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, -1));
        jPanel1.add(jtfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 220, -1));
        jPanel1.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, -1));

        jtfCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfCadastrar.setText("Cadastrar");
        jtfCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jtfCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jtfCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfCancelar.setText("Cancelar");
        jtfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jtfCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCadastrarActionPerformed
        if(FramePrincipal.CodAlterar!=0){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn;
                conn = DriverManager.getConnection("jdbc:mysql://localhost/dbautopecas", "root", "");               
                String query = "UPDATE fornecedor SET nomeFornecedor = ?, telefoneFornecedor = ?, emailFornecedor = ? WHERE idfornecedor = ?";
                PreparedStatement comando = conn.prepareStatement(query);
                comando.setString(1 , jtfNome.getText());
                comando.setString(2 , jtfTelefone.getText());
                comando.setString(3 , jtfEmail.getText());
                
                comando.setInt(4 , FramePrincipal.CodAlterar);

                comando.executeUpdate();
                
                comando.close();
                conn.close();
                
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");
                jtfNome.setText("");
                jtfTelefone.setText("");
                jtfEmail.setText("");
                

            }catch (ClassNotFoundException ex) {
              JOptionPane.showMessageDialog(null, "Não foi possível encontrar a classe Driver!");
            } catch (SQLException ex2) {
             JOptionPane.showMessageDialog(null, "Ocorreu um erro interno de SQL!"+ex2);
            }
            FramePrincipal.CodAlterar = 0;
        }else{
            try{

                Class.forName("com.mysql.jdbc.Driver"); 

                Connection conexao;

                conexao = DriverManager.getConnection("jdbc:mysql://localhost/dbautopecas","root","");

                String comando = "INSERT into fornecedor (nomeFornecedor, telefoneFornecedor, emailFornecedor)VALUES (?,?,?)";

                java.sql.PreparedStatement stmt = conexao.prepareStatement(comando);

                stmt.setString(1, jtfNome.getText());
                stmt.setString(2, jtfTelefone.getText());
                stmt.setString(3, jtfEmail.getText());


                stmt.executeUpdate();

                stmt.close();
                conexao.close();

                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                jtfNome.setText("");
                jtfTelefone.setText("");
                jtfEmail.setText("");


            }
            catch(ClassNotFoundException exClass){
                JOptionPane.showMessageDialog(null, "A classe Driver não foi encontrada!"+exClass);
            }catch(SQLException exSQL){
                JOptionPane.showMessageDialog(null, "Erro de SQL!"+exSQL);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jtfCadastrarActionPerformed

    private void jtfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jtfCancelarActionPerformed

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlCadastroFornecedor;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JButton jtfCadastrar;
    private javax.swing.JButton jtfCancelar;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
