/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 13151000014
 */
public class CadUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadUsuario
     */
    public CadUsuario() {
        initComponents();
    }
    
    public CadUsuario(String usuario, String senha) {
        initComponents();
        this.jtfUsuario.setText(usuario);
        this.jpfSenha.setText(senha);        
        //this.jtfTelefone.setText(telefone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlCadastroUsuario = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlConfirmaSenha = new javax.swing.JLabel();
        jlTipoUsuario = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jrbAdmin = new javax.swing.JRadioButton();
        jrbNormal = new javax.swing.JRadioButton();
        jpfSenha = new javax.swing.JPasswordField();
        jpfConfirmaSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(99, 113, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCadastroUsuario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlCadastroUsuario.setText("Cadastro de Usuários");
        jPanel1.add(jlCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jlUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlUsuario.setText("Usuário:");
        jPanel1.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jlSenha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlSenha.setText("Senha:");
        jPanel1.add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jlConfirmaSenha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlConfirmaSenha.setText("Confirmação de Senha:");
        jPanel1.add(jlConfirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jlTipoUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlTipoUsuario.setText("Tipo de Usuário:");
        jPanel1.add(jlTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel1.add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 280, -1));

        jbCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jrbAdmin.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbAdmin);
        jrbAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbAdmin.setText("Administrador");
        jPanel1.add(jrbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jrbNormal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbNormal);
        jrbNormal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbNormal.setText("Normal");
        jPanel1.add(jrbNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));
        jPanel1.add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 280, -1));
        jPanel1.add(jpfConfirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        if(jrbAdmin.isSelected()==false&&jrbNormal.isSelected()==false){
            JOptionPane.showMessageDialog(null, "Escolha o tipo de usuario!");
        }else{
            if(FramePrincipal.CodAlterar!=0){
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn;
                    conn = DriverManager.getConnection("jdbc:mysql://localhost/dbautopecas", "root", "");               
                    String query = "UPDATE usuario SET login = ?, senha = ?, tipoUsuario = ? WHERE idusuario = ?";
                    PreparedStatement comando = conn.prepareStatement(query);
                    comando.setString(1 , jtfUsuario.getText());
                    comando.setString(2 , jpfSenha.getText());
                    if (jrbAdmin.isSelected())
                        comando.setString(3 , "Administrador");
                    else
                        comando.setString(3, "Normal");

                    comando.setInt(4 , FramePrincipal.CodAlterar);

                    comando.executeUpdate();

                    comando.close();
                    conn.close();

                    JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");
                    jtfUsuario.setText("");
                    jpfSenha.setText("");
                    jpfConfirmaSenha.setText("");


                }catch (ClassNotFoundException ex) {
                  JOptionPane.showMessageDialog(null, "Não foi possível encontrar a classe Driver!");
                } catch (SQLException ex2) {
                 JOptionPane.showMessageDialog(null, "Ocorreu um erro interno de SQL!"+ex2);
                }
                FramePrincipal.CodAlterar = 0;
            }else{
                try{

                    Class.forName("com.mysql.jdbc.Driver"); 

                    Connection conexao;

                    conexao = DriverManager.getConnection("jdbc:mysql://localhost/dbautopecas","root","");

                    String comando = "INSERT into usuario (login, senha, tipoUsuario)VALUES (?,?,?)";

                    java.sql.PreparedStatement stmt = conexao.prepareStatement(comando);

                    stmt.setString(1, jtfUsuario.getText());
                    stmt.setString(2, jpfSenha.getText());
                    if (jrbAdmin.isSelected()){
                        stmt.setString(3, jrbAdmin.getText());
                    }else{
                        stmt.setString(3, jrbNormal.getText());
                    }

                    stmt.executeUpdate();

                    stmt.close();
                    conexao.close();

                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                    jtfUsuario.setText("");
                    jpfSenha.setText("");

                }
                catch(ClassNotFoundException exClass){
                    JOptionPane.showMessageDialog(null, "A classe Driver não foi encontrada!"+exClass);
                }catch(SQLException exSQL){
                    JOptionPane.showMessageDialog(null, "Erro de SQL!"+exSQL);
                }
            }
            this.dispose();
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JLabel jlCadastroUsuario;
    private javax.swing.JLabel jlConfirmaSenha;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTipoUsuario;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jpfConfirmaSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JRadioButton jrbAdmin;
    private javax.swing.JRadioButton jrbNormal;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
