/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 13151000014
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }
    
    public static int CodAlterar = 0;
    public static int CodVenda = 1;
    public static double valorVenda = 0;
    public static boolean verificar=false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel17 = new javax.swing.JPanel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiFuncionario = new javax.swing.JMenuItem();
        jmiPecas = new javax.swing.JMenuItem();
        jmiUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmVenda = new javax.swing.JMenu();
        jmiNovaVenda = new javax.swing.JMenuItem();
        jmiConsultVenda = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(0, 0, 102));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/autopeças.jpg"))); // NOI18N
        jPanel17.add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 240));

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("ASPIRA AUTOPEÇAS");
        jPanel17.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        getContentPane().add(jPanel17, java.awt.BorderLayout.CENTER);

        jmCadastro.setText("Cadastro");

        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCliente);

        jmiFornecedor.setText("Fornecedor");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiFornecedor);

        jmiFuncionario.setText("Funcionario");
        jmiFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiFuncionario);

        jmiPecas.setText("Peças");
        jmiPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPecasActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiPecas);

        jmiUsuario.setText("Usuário");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiUsuario);

        jMenuItem1.setText("Alterar Cadastro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmCadastro.add(jMenuItem1);

        jMenuItem2.setText("Relatórios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmCadastro.add(jMenuItem2);

        jMenuBar1.add(jmCadastro);

        jmVenda.setText("Venda");

        jmiNovaVenda.setText("Nova Venda");
        jmiNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovaVendaActionPerformed(evt);
            }
        });
        jmVenda.add(jmiNovaVenda);

        jmiConsultVenda.setText("Consulta Venda");
        jmiConsultVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultVendaActionPerformed(evt);
            }
        });
        jmVenda.add(jmiConsultVenda);

        jMenuBar1.add(jmVenda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiConsultVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultVendaActionPerformed
        Consulta consulta = new Consulta();
        consulta.setSize(400, 300);
        consulta.setResizable(false);
        consulta.setVisible(true);
        consulta.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiConsultVendaActionPerformed

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        CadCliente cliente = new CadCliente();
        cliente.setSize(375, 350);
        cliente.setResizable(false);
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        CadFornecedor fornecedor = new CadFornecedor();
        fornecedor.setSize(375, 350);
        fornecedor.setResizable(false);
        fornecedor.setVisible(true);
        fornecedor.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void jmiFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionarioActionPerformed
        CadFuncionario funcionario = new CadFuncionario();
        funcionario.setSize(375, 400);
        funcionario.setResizable(false);
        funcionario.setVisible(true);
        funcionario.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiFuncionarioActionPerformed

    private void jmiPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPecasActionPerformed
        CadPecas pecas = new CadPecas();
        pecas.setSize(375, 460);
        pecas.setResizable(false);
        pecas.setVisible(true);
        pecas.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiPecasActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        CadUsuario usuario = new CadUsuario();
        usuario.setSize(425, 350);
        usuario.setResizable(false);
        usuario.setVisible(true);
        usuario.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jmiNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovaVendaActionPerformed
        Venda venda = new Venda();
        venda.setSize(620, 450);
        venda.setResizable(false);
        venda.setVisible(true);
        venda.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmiNovaVendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AlterarCadastro alterCad = new AlterarCadastro();
        alterCad.setSize(350, 300);
        alterCad.setResizable(false);
        alterCad.setVisible(true);
        alterCad.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {  
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1/dbautopecas", "root", "");
            String query = "SELECT idvenda FROM venda";
            PreparedStatement comando = conn.prepareStatement(query);
            ResultSet resultado;
            resultado = comando.executeQuery();     

            while(resultado.next()){                 
                FramePrincipal.CodVenda++;
            } 
            comando.close();
            conn.close();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar a classe Driver!");
        } catch (SQLException ex2) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro interno de SQL!"+ex2);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        RelatoriosCad relatorio = new RelatoriosCad();
        relatorio.setSize(350, 250);
        relatorio.setResizable(false);
        relatorio.setVisible(true);
        relatorio.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmVenda;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiConsultVenda;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiFuncionario;
    private javax.swing.JMenuItem jmiNovaVenda;
    private javax.swing.JMenuItem jmiPecas;
    private javax.swing.JMenuItem jmiUsuario;
    // End of variables declaration//GEN-END:variables
}
