/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 13151000014
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        getRootPane().setDefaultButton(jbEntrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlAutenticacao = new javax.swing.JLabel();
        jlLogin = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jbEntrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtfLogin = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlAutenticacao.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlAutenticacao.setForeground(new java.awt.Color(255, 255, 255));
        jlAutenticacao.setText("Autenticação");
        jPanel1.add(jlAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 30));

        jlLogin.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(255, 255, 255));
        jlLogin.setText("Login:");
        jPanel1.add(jlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jlSenha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlSenha.setForeground(new java.awt.Color(255, 255, 255));
        jlSenha.setText("Senha:");
        jPanel1.add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jbEntrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbEntrar.setText("Entrar");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jtfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jtfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 270, -1));
        jPanel1.add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 270, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        if (jtfLogin.getText().equals("") || jpfSenha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
        else{
            try{

                Class.forName("com.mysql.jdbc.Driver"); 

                Connection conexao;

                conexao = DriverManager.getConnection("jdbc:mysql://localhost/dbautopecas","root","");

                String query = "SELECT * FROM usuario WHERE login = ?";

                PreparedStatement comando = conexao.prepareStatement(query);

                comando.setString(1, jtfLogin.getText());

                ResultSet resultado;

                resultado = comando.executeQuery();

                resultado.next();

                if(jpfSenha.getText().equals(resultado.getString("senha"))){
                    this.dispose();

                    FramePrincipal fprincipal = new FramePrincipal();
                    fprincipal.setResizable(false);
                    fprincipal.setVisible(true);
                    fprincipal.setExtendedState(MAXIMIZED_BOTH);
                    fprincipal.setLocationRelativeTo(null);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Login ou senha incorreta!");
                    jpfSenha.setText("");
                }

                comando.close();
                conexao.close();


            }
            catch(ClassNotFoundException exClass){
                JOptionPane.showMessageDialog(null, "A classe Driver não foi encontrada!"+exClass);
            }catch(SQLException exSQL){
                JOptionPane.showMessageDialog(null, "Login invalido!");
                jpfSenha.setText("");
            }
        }
        
    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JLabel jlAutenticacao;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfLogin;
    // End of variables declaration//GEN-END:variables
}
